site_name: EOEPCA Data Access Building Block
site_url: https://eoepca.readthedocs.io/projects/data-access/
repo_url: https://github.com/EOEPCA/data-access
edit_uri: "edit/main/docs/"

nav:
  - EOEPCA Documentation: https://eoepca.readthedocs.io/
  - Data Access:
    - index.md
    - Design:
      - design/overview.md
      - design/ogc-api-maps.md
    - API:
      - api/endpoint-specification.md
      - api/health-checks.md

theme:
  name: material # https://squidfunk.github.io/mkdocs-material/creating-your-site/
  navigation_depth: 4

  # For `material` theme...
  logo: img/favicon.ico
  favicon: img/favicon.ico
  features:
    # Navigation
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    # Content
    - content.code.copy
    - content.action.edit
    # Search
    - search.highlight
    - search.share
    - search.suggest

extra_css:
  - css/eoepca.css

plugins:
  - autorefs
  - search
  - swagger-ui-tag

markdown_extensions:
  - tables
  - toc:
      permalink: ⚓︎
      toc_depth: 4
  - smarty
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
