name: build eoapi custom runtime

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - runtimes/eoapi/**
      - .github/workflows/deploy-eoapi.yaml

jobs:
  build:
    name: build eoapi stac component
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: azure/docker-login@v1
        with:
          login-server: harbor.develop.eoepca.org
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: harbor.develop.eoepca.org/eoapi/stac
          tags: |
            type=ref,event=branch
            type=sha,format=short
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./runtimes/eoapi
          file: ./dockerfiles/Dockerfile.stac
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
